INSERT INTO to_borrow VALUES(1,30,51,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(2,14,53,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(3,72,35,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(4,70,46,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(1,9,9,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(5,57,19,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(6,76,96,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(7,32,79,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(8,66,63,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(9,46,92,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(1,50,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(10,77,17,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(11,52,76,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(12,5,7,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(13,73,92,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(2,60,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(14,26,38,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(15,70,5,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(16,80,88,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(17,68,2,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(18,24,69,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(19,93,34,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(20,82,76,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(21,46,34,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(22,65,53,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(3,65,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(23,71,47,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(24,35,60,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(25,28,100,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(26,44,100,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(27,99,10,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(28,49,93,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(2,15,4,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(4,63,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(29,90,33,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(30,12,32,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(31,99,83,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(3,10,5,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(5,97,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(32,33,80,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(33,67,32,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(34,31,33,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(35,52,72,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(6,3,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(36,50,93,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(37,59,92,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(38,13,54,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(39,29,29,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(40,96,10,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(41,33,84,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(42,48,58,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(43,99,9,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(44,19,65,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(45,90,41,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(46,8,64,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(47,15,4,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(48,17,98,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(49,59,23,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(50,83,28,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(51,99,82,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(52,96,67,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(53,73,78,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(54,69,33,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(7,53,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(55,58,1,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(56,74,35,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(57,81,52,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(8,46,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(58,29,47,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(59,53,61,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(60,79,8,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(61,29,46,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(62,11,85,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(63,72,64,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(64,12,57,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(65,69,50,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(66,40,33,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(67,96,24,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(68,20,19,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(4,12,4,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(9,83,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(69,16,15,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(70,13,18,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(5,97,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(71,47,11,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(72,5,45,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(73,84,65,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(74,83,78,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(75,13,48,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(76,61,60,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(77,84,89,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(78,89,81,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(79,100,74,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(80,18,31,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(81,59,18,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(82,35,24,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(83,68,18,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(84,62,50,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(85,2,2,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(86,52,79,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(87,92,86,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(88,62,10,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(6,3,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(89,38,34,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(90,6,4,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(10,78,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(91,96,31,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(92,2,3,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(11,35,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(7,7,4,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(8,92,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(93,14,99,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(94,99,66,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(95,37,67,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(96,90,30,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(97,9,61,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(98,15,73,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(99,24,20,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(9,23,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(100,90,57,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(101,27,47,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(12,1,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(10,91,9,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(11,56,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(102,8,54,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(103,76,34,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(12,4,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(104,36,69,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(105,62,37,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(106,51,32,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(107,88,100,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(108,93,51,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(109,55,90,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(110,65,40,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(111,89,70,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(112,82,62,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(113,45,91,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(13,53,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(114,55,45,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(14,64,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(115,98,77,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(15,91,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(116,18,41,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(117,59,71,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(118,86,70,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(13,76,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(119,87,82,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(120,15,37,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(121,57,100,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(16,35,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(122,16,21,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(17,31,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(123,98,93,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(124,80,62,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(125,42,59,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(126,64,50,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(127,13,15,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(128,87,76,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(129,98,91,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(130,71,36,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(131,95,11,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(132,27,68,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(18,90,4,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(133,69,56,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(19,99,3,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(134,93,29,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(14,63,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(135,26,13,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(136,57,80,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(137,72,47,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(138,58,60,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(139,62,15,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(20,72,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(140,2,64,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(15,32,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(141,39,72,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(142,98,69,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(21,6,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(143,12,19,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(144,9,36,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(145,33,14,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(146,76,47,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(147,33,68,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(148,65,98,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(149,40,83,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(150,22,75,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(151,49,35,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(152,19,59,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(153,13,33,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(154,68,32,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(16,97,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(155,37,97,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(156,43,60,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(157,68,77,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(158,72,53,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(159,77,83,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(160,16,80,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(22,53,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(161,2,15,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(162,48,80,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(163,85,9,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(164,74,98,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(165,8,8,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(166,1,56,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(167,37,33,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(17,67,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(168,22,16,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(169,72,72,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(170,98,42,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(171,59,64,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(172,65,86,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(18,86,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(173,28,3,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(174,73,21,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(175,21,65,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(176,56,9,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(177,39,15,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(178,70,99,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(179,44,78,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(19,48,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(180,74,27,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(181,19,59,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(182,6,28,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(183,42,98,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(184,22,33,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(185,15,9,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(20,57,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(186,92,19,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(187,3,83,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(23,49,4,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(188,82,1,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(189,100,10,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(190,42,64,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(191,11,88,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(192,46,21,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(193,2,13,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(21,38,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(194,54,44,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(195,41,19,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(24,2,5,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(25,43,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(196,69,76,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(197,70,75,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(198,11,6,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(26,100,8,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(199,58,89,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(200,85,6,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(201,64,26,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(202,68,94,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(203,15,46,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(204,27,95,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(22,23,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(27,44,6,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(28,12,1,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(29,64,5,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(30,18,9,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(205,8,96,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(23,63,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(206,46,83,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(207,23,14,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(208,67,56,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(209,21,2,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(210,24,7,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(211,7,38,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(212,42,4,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(24,77,FALSE);
SELECT giveback_request();
INSERT INTO giveback VALUES(25,94,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(213,33,99,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(26,69,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(214,56,2,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(215,60,79,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(216,66,14,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(27,99,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(217,38,47,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(31,14,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(218,31,62,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(219,77,39,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(28,33,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(32,74,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(220,58,9,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(221,99,48,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(33,37,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(222,16,55,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(29,32,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(223,91,34,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(224,50,2,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(225,34,67,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(226,45,61,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(227,45,98,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(228,85,89,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(229,13,99,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(230,66,34,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(30,74,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(231,63,40,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(232,44,56,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(233,72,52,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(234,84,5,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(235,8,97,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(236,63,65,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(237,30,51,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(238,99,6,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(239,88,1,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(34,24,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(240,27,55,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(241,4,38,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(242,83,32,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(243,62,30,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(31,70,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(244,6,5,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(245,56,65,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(246,25,42,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(247,94,48,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(248,47,7,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(32,30,FALSE);
SELECT giveback_request();
INSERT INTO giveback VALUES(33,17,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(35,87,8,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(249,10,20,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(250,97,32,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(251,57,90,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(252,50,99,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(253,26,21,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(254,17,83,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(255,12,100,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(256,91,58,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(257,90,39,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(258,95,47,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(259,31,80,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(260,34,49,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(261,65,45,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(262,83,95,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(263,18,28,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(264,7,45,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(36,1,8,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(265,52,77,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(37,81,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(266,26,12,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(267,89,12,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(268,37,31,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(269,56,63,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(270,41,27,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(271,68,71,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(272,50,42,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(273,32,19,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(274,57,72,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(275,13,13,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(276,16,85,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(277,65,68,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(278,24,90,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(279,67,75,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(38,23,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(280,89,2,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(281,85,67,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(282,48,74,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(283,93,23,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(284,100,90,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(34,89,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(285,100,34,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(286,76,91,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(287,92,100,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(288,1,86,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(289,40,16,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(290,93,1,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(291,63,76,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(292,55,55,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(293,57,71,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(294,63,99,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(295,58,74,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(39,83,5,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(296,30,28,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(297,31,76,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(40,74,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(298,6,30,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(41,74,8,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(299,92,95,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(42,72,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(300,80,18,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(43,89,8,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(35,97,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(301,80,12,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(302,83,23,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(303,72,64,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(304,87,48,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(305,37,11,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(44,32,3,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(306,17,64,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(307,30,21,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(308,63,20,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(309,35,86,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(310,26,8,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(311,35,30,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(312,27,85,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(313,31,61,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(45,88,2,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(46,25,8,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(36,5,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(314,96,42,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(315,16,78,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(316,25,89,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(47,66,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(317,63,7,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(318,68,10,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(319,70,93,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(37,94,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(320,12,2,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(321,63,60,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(48,56,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(322,36,39,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(38,38,FALSE);
SELECT giveback_request();
INSERT INTO giveback VALUES(39,36,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(323,81,81,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(324,45,53,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(40,64,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(49,33,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(325,70,100,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(41,54,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(326,80,57,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(327,57,70,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(328,53,48,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(329,9,18,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(330,64,80,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(42,14,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(331,35,95,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(43,42,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(50,25,9,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(332,23,92,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(333,47,72,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(334,19,5,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(335,34,37,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(336,72,23,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(337,44,19,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(338,23,3,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(339,84,51,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(340,25,1,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(341,37,40,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(342,61,98,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(343,66,15,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(344,80,32,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(345,51,27,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(346,9,14,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(347,85,82,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(348,54,86,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(349,28,86,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(350,71,56,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(351,24,27,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(352,9,98,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(353,13,71,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(354,90,97,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(44,82,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(355,48,86,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(356,63,13,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(357,20,99,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(358,97,77,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(359,16,54,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(360,24,91,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(361,81,69,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(362,80,82,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(363,88,8,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(364,39,5,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(365,9,10,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(51,33,3,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(366,5,16,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(45,22,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(367,76,49,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(368,78,1,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(369,39,31,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(46,84,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(52,63,5,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(370,3,72,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(47,32,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(371,53,94,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(372,91,98,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(373,43,3,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(374,10,22,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(48,76,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(375,47,10,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(376,58,71,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(377,70,33,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(378,68,36,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(49,12,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(379,20,11,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(380,54,1,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(381,63,86,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(382,76,56,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(383,94,87,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(53,68,9,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(384,90,63,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(385,67,72,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(386,48,68,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(387,65,22,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(388,11,13,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(389,94,84,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(390,58,1,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(391,40,61,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(54,82,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(392,41,75,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(393,57,52,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(50,91,FALSE);
SELECT giveback_request();
INSERT INTO giveback VALUES(51,74,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(394,74,100,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(395,74,52,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(396,99,1,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(397,42,2,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(398,32,16,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(399,48,25,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(52,50,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(400,22,83,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(401,43,9,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(53,10,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(402,50,4,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(54,43,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(403,69,37,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(404,73,10,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(405,42,61,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(406,53,51,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(55,18,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(407,57,84,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(408,82,96,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(409,85,85,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(410,19,57,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(56,44,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(411,12,44,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(412,60,3,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(413,38,7,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(55,69,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(414,43,63,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(415,87,79,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(56,12,8,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(416,30,55,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(417,60,87,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(418,20,100,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(57,89,9,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(419,7,16,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(420,81,45,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(421,68,24,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(422,84,53,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(57,56,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(423,79,52,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(424,78,67,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(425,36,33,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(426,33,61,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(427,96,6,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(428,83,89,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(429,3,26,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(430,50,63,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(431,32,58,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(432,57,33,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(433,51,88,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(58,73,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(434,92,65,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(435,39,77,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(436,20,4,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(59,60,3,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(437,43,67,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(438,52,72,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(58,99,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(439,33,12,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(440,55,85,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(441,20,49,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(442,13,71,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(443,61,100,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(444,82,2,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(445,75,94,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(60,79,7,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(59,68,FALSE);
SELECT giveback_request();
INSERT INTO giveback VALUES(60,66,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(446,89,76,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(447,50,57,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(448,45,100,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(449,76,24,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(450,43,95,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(451,57,32,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(452,89,2,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(453,93,10,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(454,10,43,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(455,33,19,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(456,36,36,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(457,83,5,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(458,12,44,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(61,48,3,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(61,8,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(62,57,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(459,14,53,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(460,84,12,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(461,24,21,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(462,55,44,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(463,83,5,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(464,36,38,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(465,96,69,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(466,81,98,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(63,52,6,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(62,3,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(467,63,52,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(468,7,27,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(469,36,85,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(64,7,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(470,78,55,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(63,75,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(471,43,62,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(472,94,27,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(473,74,93,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(474,9,82,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(475,91,65,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(476,27,11,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(64,80,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(477,76,5,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(478,92,42,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(65,66,4,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(479,12,74,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(480,92,84,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(481,24,10,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(482,49,68,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(483,71,21,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(484,72,65,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(485,72,99,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(486,9,23,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(487,79,4,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(488,85,3,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(489,15,94,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(490,37,31,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(491,1,80,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(492,12,74,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(493,71,4,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(65,34,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(494,47,96,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(495,7,20,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(496,30,80,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(497,27,12,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(498,60,73,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(499,45,81,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(500,73,85,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(501,78,66,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(502,5,64,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(503,62,38,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(504,1,97,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(505,44,77,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(506,80,40,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(66,56,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(507,57,25,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(508,83,90,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(509,68,80,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(510,15,18,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(511,70,80,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(512,61,58,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(67,20,4,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(68,62,7,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(69,10,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(513,100,55,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(514,58,61,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(515,83,37,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(516,32,75,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(70,69,5,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(71,5,3,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(72,15,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(517,50,64,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(518,84,94,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(66,20,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(519,4,35,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(67,23,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(520,45,63,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(521,77,64,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(73,78,9,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(522,54,7,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(523,95,58,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(524,47,39,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(525,71,23,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(526,55,1,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(527,20,69,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(528,71,17,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(74,96,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(529,92,35,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(530,97,95,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(531,94,85,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(532,74,8,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(533,68,2,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(534,100,61,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(535,88,31,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(536,39,50,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(537,64,68,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(538,53,77,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(539,48,75,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(540,18,42,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(541,26,39,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(542,44,74,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(543,47,18,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(544,35,44,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(545,66,37,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(546,77,31,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(547,36,92,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(548,85,36,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(68,14,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(549,31,52,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(550,62,33,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(551,93,48,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(552,47,38,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(553,30,21,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(554,45,84,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(555,50,53,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(556,19,88,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(557,59,25,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(558,70,16,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(559,58,48,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(560,79,95,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(561,38,29,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(562,96,92,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(75,47,5,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(563,92,91,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(564,68,7,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(565,28,83,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(566,43,30,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(567,96,40,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(568,82,50,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(569,41,89,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(570,86,84,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(76,92,8,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(571,99,73,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(572,87,89,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(573,99,2,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(574,31,33,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(77,44,5,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(575,41,53,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(576,21,13,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(577,87,97,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(578,34,96,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(579,12,57,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(69,32,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(78,62,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(580,28,14,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(581,5,82,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(582,67,99,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(583,42,57,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(584,14,79,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(585,31,7,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(586,77,69,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(587,84,23,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(588,17,11,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(79,33,9,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(589,57,45,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(590,70,58,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(591,66,42,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(80,92,9,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(70,80,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(592,71,5,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(593,98,27,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(594,91,9,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(595,66,89,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(596,97,86,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(597,43,67,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(598,66,61,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(599,16,79,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(71,1,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(600,97,78,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(81,49,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(601,84,77,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(602,61,24,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(603,4,67,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(82,73,3,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(604,9,30,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(72,34,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(605,16,58,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(606,60,71,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(607,91,35,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(608,48,10,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(609,78,37,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(73,90,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(610,6,91,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(83,48,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(611,15,38,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(612,78,53,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(613,36,9,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(614,91,77,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(84,97,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(615,10,38,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(616,20,63,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(617,97,73,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(618,75,31,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(619,25,19,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(620,84,9,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(621,48,63,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(622,72,61,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(623,98,93,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(74,1,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(624,43,86,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(625,84,88,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(626,26,20,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(627,53,70,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(628,29,74,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(629,32,77,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(630,86,50,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(631,29,66,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(632,72,26,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(633,56,66,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(634,64,6,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(85,46,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(635,64,39,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(636,28,27,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(637,100,20,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(638,74,94,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(639,25,83,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(640,18,85,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(86,43,3,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(641,53,89,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(642,81,76,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(643,77,18,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(87,85,9,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(644,53,10,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(645,87,82,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(646,38,37,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(647,57,15,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(75,12,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(88,68,8,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(89,44,6,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(76,11,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(648,3,20,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(649,16,70,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(650,46,9,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(651,28,81,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(652,77,62,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(653,56,78,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(654,47,53,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(655,87,40,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(656,86,59,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(657,11,64,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(658,7,43,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(659,25,67,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(77,100,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(660,32,74,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(661,62,11,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(78,83,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(662,85,40,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(663,88,45,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(664,80,33,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(665,85,24,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(666,67,18,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(667,26,4,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(668,70,19,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(79,14,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(669,43,44,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(670,18,98,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(671,84,21,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(672,93,94,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(673,99,4,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(674,38,6,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(675,42,39,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(676,14,57,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(677,57,81,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(678,93,25,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(80,8,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(679,96,29,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(81,79,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(680,10,14,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(681,61,46,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(82,63,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(682,2,75,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(83,47,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(683,26,44,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(684,40,5,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(84,53,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(685,32,91,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(85,16,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(686,59,20,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(687,30,48,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(688,85,47,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(689,1,74,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(690,60,54,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(691,27,99,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(692,61,41,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(693,97,92,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(694,31,7,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(695,41,72,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(696,50,18,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(697,58,37,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(86,97,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(698,44,59,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(699,61,64,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(700,10,52,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(701,22,46,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(702,75,100,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(703,56,34,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(704,46,92,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(705,97,66,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(706,39,51,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(707,91,73,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(708,11,48,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(709,68,8,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(710,40,74,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(711,11,88,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(712,17,65,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(87,45,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(713,71,4,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(714,32,73,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(715,45,54,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(716,4,27,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(88,49,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(717,27,85,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(90,20,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(718,85,86,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(719,73,90,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(720,89,75,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(721,44,24,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(722,95,33,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(723,61,5,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(724,4,46,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(725,34,83,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(89,97,FALSE);
SELECT giveback_request();
INSERT INTO purchase VALUES(91,19,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(726,37,23,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(90,20,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(727,58,79,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(728,63,37,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(729,41,56,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(730,31,42,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(91,21,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(731,3,90,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(92,11,7,FALSE);
SELECT purchase_request();
INSERT INTO giveback VALUES(92,92,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(732,68,30,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(93,43,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(733,39,7,2,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(94,68,2,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(734,76,79,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(735,93,57,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(736,77,69,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(737,91,77,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(738,64,97,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(739,78,11,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(740,42,26,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(741,11,88,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(742,62,47,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(743,96,17,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(744,53,92,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(745,63,60,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(746,31,22,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(747,17,64,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(748,77,31,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(749,30,88,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(750,99,27,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(751,18,4,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(752,57,82,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(93,11,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(753,20,96,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(94,63,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(754,87,79,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(755,46,2,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(756,22,13,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(757,76,39,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(758,24,48,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(759,51,19,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(760,6,1,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(761,7,70,1,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(95,97,5,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(762,56,83,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(763,29,50,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(764,55,80,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(96,40,4,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(765,50,88,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(95,73,FALSE);
SELECT giveback_request();
INSERT INTO giveback VALUES(96,21,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(766,65,2,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(97,38,7,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(767,57,91,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(768,88,27,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(769,15,18,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(770,97,37,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(771,29,3,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(98,78,2,FALSE);
SELECT purchase_request();
INSERT INTO purchase VALUES(99,47,1,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(772,61,43,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(773,48,38,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(774,91,59,3,FALSE);
SELECT borrow_request();
INSERT INTO purchase VALUES(100,65,6,FALSE);
SELECT purchase_request();
INSERT INTO to_borrow VALUES(775,52,26,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(776,34,24,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(777,42,91,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(778,74,87,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(779,71,83,2,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(97,48,FALSE);
SELECT giveback_request();
INSERT INTO giveback VALUES(98,84,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(780,62,87,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(781,69,96,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(782,19,47,1,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(99,76,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(783,90,9,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(784,36,59,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(785,53,8,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(786,48,82,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(787,20,43,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(788,94,27,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(789,16,3,3,FALSE);
SELECT borrow_request();
INSERT INTO giveback VALUES(100,24,FALSE);
SELECT giveback_request();
INSERT INTO to_borrow VALUES(790,76,8,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(791,20,41,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(792,40,54,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(793,11,68,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(794,94,100,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(795,28,50,2,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(796,73,20,1,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(797,90,73,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(798,71,38,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(799,33,2,3,FALSE);
SELECT borrow_request();
INSERT INTO to_borrow VALUES(800,7,96,3,FALSE);
SELECT borrow_request();
